version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - db-volume:/var/lib/postgresql/data 
    ports:
      - "5432:5432"
    networks:
      - tc3-network

  api:
    build: .
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - tc3-network
    restart: always

  web:
    build: .
    ports:
      - 8501:8501
    volumes:
      - .:/app
    command: streamlit run src/interface.py
    depends_on:
      - api
    networks:
      - tc3-network

volumes:
  db-volume:

networks:
  tc3-network: